### ISSUE TITLE
is-my-json-valid error

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint-tester#26]
I tried doing a patch release this morning, and got this dump:

```
$ npm test

> eslint-tester@0.8.1 test c:\Users\Nicholas\projects\personal\eslint-tester
> node Makefile.js test

No coverage information was collected, exit without writing coverage information


module.js:340
    throw err;
          ^
Error: Cannot find module 'is-my-json-valid'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\Nicholas\projects\personal\jscheck\lib\confi
g-validator.js:10:23)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (c:\Users\Nicholas\projects\personal\eslint
-tester\node_modules\istanbul\lib\hook.js:102:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\Nicholas\projects\personal\jscheck\lib\eslin
t.js:22:17)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (c:\Users\Nicholas\projects\personal\eslint
-tester\node_modules\istanbul\lib\hook.js:102:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\Nicholas\projects\personal\jscheck\lib\api.j
s:9:13)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (c:\Users\Nicholas\projects\personal\eslint
-tester\node_modules\istanbul\lib\hook.js:102:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\Nicholas\projects\personal\eslint-tester\tes
ts\lib\eslint-tester.js:15:14)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (c:\Users\Nicholas\projects\personal\eslint
-tester\node_modules\istanbul\lib\hook.js:102:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\mocha\lib\
mocha.js:172:27
    at Array.forEach (native)
    at Mocha.loadFiles (c:\Users\Nicholas\projects\personal\eslint-tester\node_m
odules\mocha\lib\mocha.js:169:14)
    at Mocha.run (c:\Users\Nicholas\projects\personal\eslint-tester\node_modules
\mocha\lib\mocha.js:356:31)
    at Object.<anonymous> (c:\Users\Nicholas\projects\personal\eslint-tester\nod
e_modules\mocha\bin\_mocha:359:16)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (c:\Users\Nicholas\projects\personal\eslint
-tester\node_modules\istanbul\lib\hook.js:102:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\ist
anbul\lib\command\common\run-with-cover.js:116:16)
    at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\istanbul\l
ib\command\common\run-with-cover.js:239:17
    at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\istanbul\l
ib\util\file-matcher.js:68:16
    at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\istanbul\n
ode_modules\async\lib\async.js:254:17
    at done (c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\ista
nbul\node_modules\async\lib\async.js:135:19)
    at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\istanbul\n
ode_modules\async\lib\async.js:32:16
    at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\istanbul\n
ode_modules\async\lib\async.js:251:21
    at LOOP (fs.js:1369:14)
    at process._tickCallback (node.js:419:13)
```

I tried manually installing `is-my-json-valid`, but it didn't help.

@btmills can you take a look?

Note: I'm on Windows, if that matters.

**Comment by btmills** [comment]
I was able to repro this by deleting eslint's copy of `is-my-json-valid`. Have you `npm install`ed from your eslint checkout since validation shipped?

**Comment by btmills** [comment]
Could this be a symptom of #24?

**Comment by nzakas** [comment]
Ah, I see. I dint think I've updated the ESLint one.

Yuck, this relationship is a nightmare.

**Comment by btmills** [comment]
Yeah. If that fixes it I don't think there's any reason to hold up a patch release, but I'm starting to lean more toward merging them back together soon.

**Comment by nzakas** [comment]
Next error:

```
  1) ESLintTester should pass-through the parser to the rule:
     AssertionError: expected [Function] to not throw an error but 'AssertionErr
or: A fatal parsing error occurred: Cannot find module \'esprima\': expected fal
se to be truthy' was thrown
      at Function.assert.doesNotThrow (c:\Users\Nicholas\projects\personal\eslin
t-tester\node_modules\chai\lib\chai\interface\assert.js:951:35)
      at Context.<anonymous> (c:\Users\Nicholas\projects\personal\eslint-tester\
tests\lib\eslint-tester.js:336:16)
      at Test.Runnable.run (c:\Users\Nicholas\projects\personal\eslint-tester\no
de_modules\mocha\lib\runnable.js:221:32)
      at Runner.runTest (c:\Users\Nicholas\projects\personal\eslint-tester\node_
modules\mocha\lib\runner.js:374:10)
      at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\mocha\li
b\runner.js:452:12
      at next (c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\mo
cha\lib\runner.js:299:14)
      at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\mocha\li
b\runner.js:309:7
      at next (c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\mo
cha\lib\runner.js:247:23)
      at c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\mocha\li
b\runner.js:271:7
      at Hook.Runnable.run (c:\Users\Nicholas\projects\personal\eslint-tester\no
de_modules\mocha\lib\runnable.js:223:5)
      at next (c:\Users\Nicholas\projects\personal\eslint-tester\node_modules\mo
cha\lib\runner.js:259:10)
      at Object._onImmediate (c:\Users\Nicholas\projects\personal\eslint-tester\
node_modules\mocha\lib\runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by btmills** [comment]
I get that error if I remove esprima from eslint's `node_modules` folder.

**Comment by nzakas** [comment]
Hmm, no idea what's going on, and I'm too exhausted to try and figure it out at the moment. I'll take another stab when I get a burst of energy.

**Comment by nzakas** [comment]
Got it figured out.
